export const RESPONSE_MESSAGE = {
  FILE_IS_NOT_VALID: 'File is not valid',
  EMAIL_IS_INVALID: 'Email is invalid',
  EMAIL_IS_REQUIRED: 'Email is required',
  USER_ID_IS_REQUIRED: 'User ID is required',
  URL_IS_REQUIRED: 'URL is required',
  STATUS_IS_REQUIRED: 'Status is required',
  COMPANY_ID_IS_REQUIRED: 'Company ID is required',
  JOB_ID_IS_REQUIRED: 'Job ID is required',
  HISTORY_IS_REQUIRED: 'History is required',
  NAME_IS_REQUIRED: 'Name is required',
  SKILLS_IS_ARRAY: 'Skills is array',
  SKILLS_IS_REQUIRED: 'Skills is required',
  COMPANY_IS_REQUIRED: 'Company is required',
  LOCATION_IS_REQUIRED: 'Location is required',
  SALARY_IS_REQUIRED: 'Salary is required',
  QUANTITY_IS_REQUIRED: 'Quantity is required',
  LEVEL_IS_REQUIRED: 'Level is required',
  DESCRIPTION_IS_REQUIRED: 'Description is required',
  START_DATE_IS_REQUIRED: 'StartDate is required',
  END_DATE_IS_REQUIRED: 'EndDate is required',
  ID_IS_INVALID: 'ID is invalid'
}
